import { Product, Category } from '../types';

export const DEMO_CATEGORIES: Category[] = [
  {
    id: '92c34d16-9703-4a8a-bef6-0dc22c9e8ee9',
    name: 'Clothing',
    slug: 'clothing',
    icon_name: 'Shirt',
    sort_order: 1,
    image_url: 'https://images.pexels.com/photos/5693891/pexels-photo-5693891.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Cotton tops, frock sets, dungarees & lounge wear',
    brand_tagline: 'JOJI KIDS FASHION',
  },
  {
    id: 'e89a1122-3344-5566-7788-99aabbccddee',
    name: 'Ethnic & Festive',
    slug: 'ethnic-wear',
    icon_name: 'Crown',
    sort_order: 2,
    image_url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&auto=format&fit=crop&q=80',
    description: 'Festive lehengas, Janmashtami Krishna sets & royal celebration wear',
    brand_tagline: 'FESTIVE CELEBRATIONS',
  },
  {
    id: '0c7b29e0-71d1-495c-9c9b-5cbbfa3bc0d6',
    name: 'Footwear',
    slug: 'footwear',
    icon_name: 'Footprints',
    sort_order: 3,
    image_url: 'https://images.pexels.com/photos/19869753/pexels-photo-19869753.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'LED light sneakers, anti-slip kicks & booties',
    brand_tagline: 'LITTLE STEPS COMFORT',
  },
  {
    id: '1829ce49-af70-4727-882d-0eeb5fd3151d',
    name: 'Toys',
    slug: 'toys',
    icon_name: 'ToyBrick',
    sort_order: 3,
    image_url: 'https://images.pexels.com/photos/35619/cap-race-car-model-car-fast.jpg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'RC turbo cars, plush soft bears & STEM puzzles',
    brand_tagline: 'JOJI TOY ZONE',
  },
  {
    id: 'adf061c8-b69f-4517-86c0-ae071687d1e5',
    name: 'Accessories',
    slug: 'accessories',
    icon_name: 'Backpack',
    sort_order: 4,
    image_url: 'https://images.pexels.com/photos/8471799/pexels-photo-8471799.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Dino preschool bags, UV sunglasses & bucket hats',
    brand_tagline: 'PLAYTIME GEAR',
  },
  {
    id: '280aa880-014d-4080-bd2d-ab08ab485dbb',
    name: 'Baby Care',
    slug: 'baby-care',
    icon_name: 'Baby',
    sort_order: 5,
    image_url: 'https://images.pexels.com/photos/3845492/pexels-photo-3845492.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Organic bamboo swaddles & gentle lotions',
    brand_tagline: 'JOJI BABY CARE',
  },
  {
    id: 'c9ee89df-ab64-4e0f-9f29-02e667b85b27',
    name: 'Gifting',
    slug: 'gifting',
    icon_name: 'Gift',
    sort_order: 6,
    image_url: 'https://images.pexels.com/photos/6157049/pexels-photo-6157049.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Hamper boxes, newborn welcome kits & party sets',
    brand_tagline: 'CELEBRATION BOXES',
  },
];

export const DEMO_CATALOG_PRODUCTS: Product[] = [
  // ==================== CLOTHING ====================
  {
    id: 'demo-cloth-1',
    name: 'Boys Striped Polo Collar T-Shirt & Chino Shorts Set',
    brand: 'JOJI KIDS',
    description: '100% breathable combed cotton with wooden-look buttons and elasticated waistband shorts for all-day active play.',
    price: 649,
    old_price: 999,
    discount_percent: 35,
    image_url: 'https://images.pexels.com/photos/5693891/pexels-photo-5693891.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'BESTSELLER',
    color_theme: 'amber',
    category_id: '92c34d16-9703-4a8a-bef6-0dc22c9e8ee9',
    gender: 'boys',
    age_group: '2-4Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-cloth-2',
    name: 'Girls Pastel Floral Twirl Party Frock with Matching Bow',
    brand: 'JOJI KIDS',
    description: 'Soft satin-lined cotton dress with flared tiered hem and gentle non-scratch neck stitching. Perfect for birthday parties.',
    price: 799,
    old_price: 1299,
    discount_percent: 38,
    image_url: 'https://images.pexels.com/photos/5693888/pexels-photo-5693888.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'TRENDING',
    color_theme: 'rose',
    category_id: '92c34d16-9703-4a8a-bef6-0dc22c9e8ee9',
    gender: 'girls',
    age_group: '3-6Y',
    rating: 4.8,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-cloth-3',
    name: 'Classic Vintage Wash Denim Dungaree with Striped Inner Tee',
    brand: 'JOJI KIDS',
    description: 'Durable stretch denim with adjustable brass clasps and 5 utility pockets. Soft inner knit cotton tee included.',
    price: 899,
    old_price: 1499,
    discount_percent: 40,
    image_url: 'https://images.pexels.com/photos/18533669/pexels-photo-18533669.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'HOT DEAL',
    color_theme: 'blue',
    category_id: '92c34d16-9703-4a8a-bef6-0dc22c9e8ee9',
    gender: 'unisex',
    age_group: '1-3Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-cloth-4',
    name: 'Dino Explorer Organic Cotton Lounge Pajamas - Pack of 2',
    brand: 'JOJI KIDS',
    description: 'Ultra-soft rib-cuff jogger pants with organic dyes, gentle elastic band that prevents marks on tender skin.',
    price: 599,
    old_price: 899,
    discount_percent: 33,
    image_url: 'https://images.pexels.com/photos/18533668/pexels-photo-18533668.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'NEW',
    color_theme: 'emerald',
    category_id: '92c34d16-9703-4a8a-bef6-0dc22c9e8ee9',
    gender: 'unisex',
    age_group: '2-5Y',
    rating: 4.7,
    is_bestseller: false,
    is_active: true,
  },

  // ==================== ETHNIC & FESTIVE WEAR ====================
  {
    id: 'demo-festive-1',
    name: 'Girls Festive Peplum Lehenga Choli & Twirl Skirt Set with Dupatta',
    brand: 'JOJI ETHNIC',
    description: '100% soft cotton festive flair lehenga set featuring gold tree print peplum sleeveless blouse, twirl-ready flared navy blue ghagra with golden zari border, and vibrant fuchsia pink dupatta.',
    price: 999,
    old_price: 1899,
    discount_percent: 47,
    image_url: 'https://images.pexels.com/photos/8819389/pexels-photo-8819389.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'FESTIVE',
    color_theme: 'rose',
    category_id: 'e89a1122-3344-5566-7788-99aabbccddee',
    gender: 'girls',
    age_group: '2-8Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-festive-2',
    name: 'Royal Janmashtami Krishna Costume Set with Mukut, Bansuri, Haar & Bajuband',
    brand: 'JOJI FESTIVE',
    description: 'Complete 7-piece divine Bal Gopal Krishna costume jewelry accessory kit: includes embroidered golden mukut crown with real peacock feather, embellished golden flute bansuri, triple-strand pearl necklace, matching stone bajuband armlets, and waist kamarbandh.',
    price: 649,
    old_price: 1199,
    discount_percent: 46,
    image_url: 'https://images.pexels.com/photos/1037992/pexels-photo-1037992.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'SPECIAL',
    color_theme: 'amber',
    category_id: 'e89a1122-3344-5566-7788-99aabbccddee',
    gender: 'boys',
    age_group: '1-6Y',
    rating: 5.0,
    is_bestseller: true,
    is_active: true,
  },

  // ==================== FOOTWEAR ====================
  {
    id: 'demo-foot-1',
    name: 'Light-Up LED Kids High-Top Casual Sneakers',
    brand: 'JOJI KIDS',
    description: 'Shock-absorbing memory foam insole with responsive LED light soles activated on each bounce. Dual Velcro straps for easy slip-on.',
    price: 849,
    old_price: 1399,
    discount_percent: 39,
    image_url: 'https://images.pexels.com/photos/19869753/pexels-photo-19869753.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'BESTSELLER',
    color_theme: 'amber',
    category_id: '0c7b29e0-71d1-495c-9c9b-5cbbfa3bc0d6',
    gender: 'unisex',
    age_group: '3-7Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-foot-2',
    name: 'Anti-Slip Playground Breathable Mesh Running Shoes',
    brand: 'JOJI KIDS',
    description: 'Lightweight air-mesh upper prevents sweaty feet. High-traction rubber outsole tested against slippery surfaces.',
    price: 699,
    old_price: 1199,
    discount_percent: 41,
    image_url: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'POPULAR',
    color_theme: 'blue',
    category_id: '0c7b29e0-71d1-495c-9c9b-5cbbfa3bc0d6',
    gender: 'boys',
    age_group: '4-8Y',
    rating: 4.8,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-foot-3',
    name: 'Soft Sole First-Step Pre-Walker Leather Baby Booties',
    brand: 'JOJI KIDS',
    description: 'Approved by pediatric podiatrists for healthy arch development. Feather-light design with zero pinch points.',
    price: 499,
    old_price: 799,
    discount_percent: 37,
    image_url: 'https://images.pexels.com/photos/3771691/pexels-photo-3771691.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'NEW',
    color_theme: 'amber',
    category_id: '0c7b29e0-71d1-495c-9c9b-5cbbfa3bc0d6',
    gender: 'unisex',
    age_group: '0-18M',
    rating: 4.9,
    is_bestseller: false,
    is_active: true,
  },
  {
    id: 'demo-foot-4',
    name: 'Sparkle Glitter Party Ballerina Flats with Comfort Cushions',
    brand: 'JOJI KIDS',
    description: 'Anti-blister padded collar and flexible non-marking sole. Shimmer finish that does not flake off.',
    price: 649,
    old_price: 999,
    discount_percent: 35,
    image_url: 'https://images.pexels.com/photos/6045028/pexels-photo-6045028.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'TRENDING',
    color_theme: 'rose',
    category_id: '0c7b29e0-71d1-495c-9c9b-5cbbfa3bc0d6',
    gender: 'girls',
    age_group: '3-6Y',
    rating: 4.7,
    is_bestseller: false,
    is_active: true,
  },

  // ==================== TOYS ====================
  {
    id: 'demo-toy-1',
    name: 'High-Speed 2.4GHz RC Turbo Stunt Racing Car with 360° Flip',
    brand: 'JOJI TOYS',
    description: 'Double-sided driving, blazing LED headlights, rechargeable battery pack, and anti-crash rubber tires. Safe non-toxic ABS plastic.',
    price: 899,
    old_price: 1599,
    discount_percent: 43,
    image_url: 'https://images.pexels.com/photos/35619/cap-race-car-model-car-fast.jpg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'BESTSELLER',
    color_theme: 'rose',
    category_id: '1829ce49-af70-4727-882d-0eeb5fd3151d',
    gender: 'unisex',
    age_group: '4-10Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-toy-2',
    name: 'Giant Cuddle Teddy Bear Soft Toy with Satin Neck Ribbon (45cm)',
    brand: 'JOJI TOYS',
    description: 'Ultra-plush hypoallergenic poly-fiber filling. Child-safe embroidered eyes and nose with no choke hazards.',
    price: 749,
    old_price: 1199,
    discount_percent: 37,
    image_url: 'https://images.pexels.com/photos/1487848/pexels-photo-1487848.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'HOT DEAL',
    color_theme: 'amber',
    category_id: '1829ce49-af70-4727-882d-0eeb5fd3151d',
    gender: 'unisex',
    age_group: '1-8Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-toy-3',
    name: 'STEM Educational Wooden Magnetic Alphabet & Math Puzzle Board',
    brand: 'JOJI TOYS',
    description: 'Smooth natural beechwood with water-based non-toxic paint. Encourages fine motor coordination and early word recognition.',
    price: 549,
    old_price: 899,
    discount_percent: 38,
    image_url: 'https://images.pexels.com/photos/8613089/pexels-photo-8613089.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'LEARNING',
    color_theme: 'emerald',
    category_id: '1829ce49-af70-4727-882d-0eeb5fd3151d',
    gender: 'unisex',
    age_group: '2-5Y',
    rating: 4.8,
    is_bestseller: false,
    is_active: true,
  },
  {
    id: 'demo-toy-4',
    name: 'Multi-Activity Interactive Musical Piano & Sound Safari Station',
    brand: 'JOJI TOYS',
    description: 'Vibrant animal sounds, nursery tunes, flashing rhythm keys, and soft silicone teething edges. Volume limit safe for baby ears.',
    price: 799,
    old_price: 1299,
    discount_percent: 38,
    image_url: 'https://images.pexels.com/photos/3662849/pexels-photo-3662849.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'NEW',
    color_theme: 'amber',
    category_id: '1829ce49-af70-4727-882d-0eeb5fd3151d',
    gender: 'unisex',
    age_group: '1-3Y',
    rating: 4.8,
    is_bestseller: false,
    is_active: true,
  },

  // ==================== ACCESSORIES ====================
  {
    id: 'demo-acc-1',
    name: '3D Cute Dinosaur Waterproof Preschool Backpack',
    brand: 'JOJI KIDS',
    description: 'Ergonomic breathable back padding with anti-lost safety chest buckle and insulated side bottle pouch. Lightweight 280g.',
    price: 599,
    old_price: 999,
    discount_percent: 40,
    image_url: 'https://images.pexels.com/photos/8471799/pexels-photo-8471799.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'BESTSELLER',
    color_theme: 'emerald',
    category_id: 'adf061c8-b69f-4517-86c0-ae071687d1e5',
    gender: 'unisex',
    age_group: '2-6Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-acc-2',
    name: 'Bendable UV400 Polarized Sunglasses with Secure Silicone Strap',
    brand: 'JOJI KIDS',
    description: 'Unbreakable food-grade TPE frame that bends without snapping. 100% UVA & UVB protection for beach and sunny outings.',
    price: 349,
    old_price: 599,
    discount_percent: 41,
    image_url: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'HOT DEAL',
    color_theme: 'amber',
    category_id: 'adf061c8-b69f-4517-86c0-ae071687d1e5',
    gender: 'unisex',
    age_group: '2-8Y',
    rating: 4.7,
    is_bestseller: false,
    is_active: true,
  },
  {
    id: 'demo-acc-3',
    name: 'Embroidered Cotton Bucket Sun Hat with Breathable Eyelets',
    brand: 'JOJI KIDS',
    description: 'UPF 50+ sun protection with wide brim to shield delicate neck and face. Quick-drying washable cotton fabric.',
    price: 399,
    old_price: 649,
    discount_percent: 38,
    image_url: 'https://images.pexels.com/photos/1619801/pexels-photo-1619801.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'SUMMER',
    color_theme: 'amber',
    category_id: 'adf061c8-b69f-4517-86c0-ae071687d1e5',
    gender: 'unisex',
    age_group: '1-5Y',
    rating: 4.8,
    is_bestseller: false,
    is_active: true,
  },

  // ==================== BABY CARE ====================
  {
    id: 'demo-baby-1',
    name: 'Organic Bamboo Muslin Swaddle Blankets (Set of 3)',
    brand: 'JOJI CARE',
    description: 'Pre-washed extra-large (120x120cm) bamboo-cotton swaddles that get softer with each laundry cycle. Gentle on sensitive skin.',
    price: 799,
    old_price: 1299,
    discount_percent: 38,
    image_url: 'https://images.pexels.com/photos/3845492/pexels-photo-3845492.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'BESTSELLER',
    color_theme: 'emerald',
    category_id: '280aa880-014d-4080-bd2d-ab08ab485dbb',
    gender: 'unisex',
    age_group: '0-12M',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-baby-2',
    name: 'Tear-Free Organic Aloe & Coconut Baby Body Wash & Lotion Duo',
    brand: 'JOJI CARE',
    description: 'Pediatrician tested, hypoallergenic, zero parabens, zero phthalates. Leaves baby skin naturally nourished and hydrated.',
    price: 499,
    old_price: 799,
    discount_percent: 37,
    image_url: 'https://images.pexels.com/photos/3662852/pexels-photo-3662852.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'NON-TOXIC',
    color_theme: 'blue',
    category_id: '280aa880-014d-4080-bd2d-ab08ab485dbb',
    gender: 'unisex',
    age_group: '0-3Y',
    rating: 4.8,
    is_bestseller: false,
    is_active: true,
  },
  {
    id: 'demo-baby-3',
    name: 'Cotton Front-Tie Thermal Innerwear Jhabla & Bloomer Set',
    brand: 'JOJI BABY',
    description: 'Super-soft pastel blue ribbed cotton thermal kimono jhabla wrap top with gentle side tie-up cords. Designed for newborns and infants with delicate skin.',
    price: 399,
    old_price: 699,
    discount_percent: 43,
    image_url: 'https://images.pexels.com/photos/3845492/pexels-photo-3845492.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'ESSENTIAL',
    color_theme: 'blue',
    category_id: '280aa880-014d-4080-bd2d-ab08ab485dbb',
    gender: 'unisex',
    age_group: '0-12M',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-baby-4',
    name: 'Waterproof Dual-Layer Cotton Feeder Bibs & Burp Cloths (Set of 3)',
    brand: 'JOJI BABY',
    description: 'Ultra-absorbent organic terry cloth backing with soft cotton embroidered front. Protects clothes from drool, spills, and baby burps.',
    price: 299,
    old_price: 499,
    discount_percent: 40,
    image_url: 'https://images.pexels.com/photos/3662852/pexels-photo-3662852.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'VALUE PACK',
    color_theme: 'cyan',
    category_id: '280aa880-014d-4080-bd2d-ab08ab485dbb',
    gender: 'unisex',
    age_group: '0-2Y',
    rating: 4.8,
    is_bestseller: false,
    is_active: true,
  },
  {
    id: 'demo-baby-5',
    name: 'Duck Ergonomic Toddler Potty Training Chair with Splash Guard',
    brand: 'JOJI CARE',
    description: 'Playful duck-themed potty trainer with high backrest support, removable bowl for effortless cleaning, and anti-slip rubber grip base.',
    price: 699,
    old_price: 1199,
    discount_percent: 42,
    image_url: 'https://images.pexels.com/photos/8613089/pexels-photo-8613089.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'POPULAR',
    color_theme: 'amber',
    category_id: '280aa880-014d-4080-bd2d-ab08ab485dbb',
    gender: 'unisex',
    age_group: '1-4Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },

  // ==================== GIFTING ====================
  {
    id: 'demo-gift-1',
    name: 'Royal Welcome Newborn Baby Gift Hamper Box (9 Pieces)',
    brand: 'JOJI KIDS',
    description: 'Includes 2 onesies, mittens, booties, bib, plush rattle, organic swaddle, milestone card, and reusable keepsake box with ribbon.',
    price: 1199,
    old_price: 1999,
    discount_percent: 40,
    image_url: 'https://images.pexels.com/photos/6157049/pexels-photo-6157049.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'BESTSELLER',
    color_theme: 'amber',
    category_id: 'c9ee89df-ab64-4e0f-9f29-02e667b85b27',
    gender: 'unisex',
    age_group: '0-6M',
    rating: 5.0,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 'demo-gift-2',
    name: 'Little Champions Birthday Celebration Outfit & Toy Hamper',
    brand: 'JOJI KIDS',
    description: 'Complete party outfit set paired with a mini friction sports car, birthday crown, and customizable greeting card.',
    price: 1049,
    old_price: 1699,
    discount_percent: 38,
    image_url: 'https://images.pexels.com/photos/7139885/pexels-photo-7139885.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tag: 'CELEBRATION',
    color_theme: 'rose',
    category_id: 'c9ee89df-ab64-4e0f-9f29-02e667b85b27',
    gender: 'unisex',
    age_group: '2-5Y',
    rating: 4.9,
    is_bestseller: true,
    is_active: true,
  },
];
